const {addition}=require("./addition")
const {subtraction}=require("./subtraction")
const {multiplication}=require("./multiplication")
const {division}=require("./division")
const {modulo}=require("./modulo")
console.log("the numbers are 5 and 2 and operations on them are mention below")
console.log("addition of the numbers is " +addition(5,2))
console.log("multiplication of the numbers is " +multiplication(5,2))
console.log("division of the numbers is " +division(5,2))
console.log("subtraction of the numbers is " +subtraction(5,2))
console.log("modulo of the numbers is " +modulo(5,2))